name: advplus
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  flutter_svg: ^2.0.5
  intl: ^0.20.2
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  google_sign_in: ^6.3.0
  provider: ^6.1.1 # Opcional, pero útil para manejar estado global del usuario

  
  cupertino_icons: ^1.0.8

dev_dependencies:
  change_app_package_name: ^1.5.0
  
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/data/motivationalphrases.json

  fonts:
    - family: Fredoka
      fonts:
        - asset: assets/fonts/Fredoka-Regular.ttf
        - asset: assets/fonts/Fredoka-SemiBold.ttf


       
